[0m12:16:22.680614 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DBEFC367B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DBED931D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DBF0BC7ED0>]}


============================== 12:16:22.687358 | 92444455-dcbb-4e63-bf47-c869af28a34d ==============================
[0m12:16:22.687358 [info ] [MainThread]: Running with dbt=1.9.6
[0m12:16:22.688342 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\jenny\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:16:28.439913 [debug] [MainThread]: Starter project path: c:\Users\jenny\.vscode\dvdrental\.venv\Lib\site-packages\dbt\include\starter_project
[0m12:16:28.461412 [info ] [MainThread]: 
Your new dbt project "dvdrental" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:16:28.468148 [info ] [MainThread]: Setting up your profile.
[0m12:16:32.000210 [debug] [MainThread]: Command `dbt init` succeeded at 12:16:31.999996 after 9.50 seconds
[0m12:16:32.000948 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DBF0C550F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DBF1E01C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DBF0C4F350>]}
[0m12:16:32.001652 [debug] [MainThread]: Flushing usage events
[0m12:16:32.414809 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:26:16.643619 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245AD3967B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245AB091D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245AE327ED0>]}


============================== 12:26:16.650411 | 2b34ab42-db13-4122-b9e8-881a6819b0c0 ==============================
[0m12:26:16.650411 [info ] [MainThread]: Running with dbt=1.9.6
[0m12:26:16.651196 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\jenny\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt clean', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:26:16.651841 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jenny\.vscode\dvdrental\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:26:16.653515 [debug] [MainThread]: Command `dbt clean` failed at 12:26:16.653358 after 0.20 seconds
[0m12:26:16.654114 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245AE1DBA80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245AE34CDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245AE16F460>]}
[0m12:26:16.654529 [debug] [MainThread]: Flushing usage events
[0m12:26:17.090315 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:05:45.575919 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107e77700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f02170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f01a20>]}


============================== 13:05:45.579099 | 0cf87128-5b5a-4b7c-98f8-c65aa82c0179 ==============================
[0m13:05:45.579099 [info ] [MainThread]: Running with dbt=1.9.8
[0m13:05:45.579448 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/samstreumer/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:05:45.588203 [info ] [MainThread]: dbt version: 1.9.8
[0m13:05:45.588443 [info ] [MainThread]: python version: 3.10.0
[0m13:05:45.588617 [info ] [MainThread]: python path: /Users/samstreumer/.pyenv/versions/3.10.0/bin/python
[0m13:05:45.588787 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m13:05:45.588958 [info ] [MainThread]: Using profiles dir at /Users/samstreumer/.dbt
[0m13:05:45.589121 [info ] [MainThread]: Using profiles.yml file at /Users/samstreumer/.dbt/profiles.yml
[0m13:05:45.589476 [info ] [MainThread]: Using dbt_project.yml file at /Users/samstreumer/Documents/SchoolFolder/dvdrental/dbt_project.yml
[0m13:05:45.589699 [info ] [MainThread]: Configuration:
[0m13:05:45.589855 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m13:05:45.589999 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:05:45.590140 [info ] [MainThread]: Required dependencies:
[0m13:05:45.590336 [debug] [MainThread]: Executing "git --help"
[0m13:05:45.597651 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:05:45.598177 [debug] [MainThread]: STDERR: "b''"
[0m13:05:45.598374 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:05:45.598562 [info ] [MainThread]: Connection test skipped since no profile was found
[0m13:05:45.598785 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:05:45.598945 [info ] [MainThread]: dbt looked for a profiles.yml file in /Users/samstreumer/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m13:05:45.599102 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/samstreumer/Documents/SchoolFolder/dvdrental/dbt_project.yml> not found

[0m13:05:45.599972 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.061645877, "process_in_blocks": "0", "process_kernel_time": 0.095973, "process_mem_max_rss": "97959936", "process_out_blocks": "0", "process_user_time": 0.753357}
[0m13:05:45.600336 [debug] [MainThread]: Command `dbt debug` failed at 13:05:45.600281 after 0.06 seconds
[0m13:05:45.600594 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107e77700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f01000>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f5e110>]}
[0m13:05:45.600829 [debug] [MainThread]: Flushing usage events
[0m13:05:46.054627 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:18:36.497685 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104f778e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077c3970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077c2fb0>]}


============================== 13:18:36.501113 | 76118e1a-8486-4f41-97d5-ea2bf8b9b777 ==============================
[0m13:18:36.501113 [info ] [MainThread]: Running with dbt=1.9.8
[0m13:18:36.501469 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/samstreumer/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:18:36.509840 [info ] [MainThread]: dbt version: 1.9.8
[0m13:18:36.510090 [info ] [MainThread]: python version: 3.10.0
[0m13:18:36.510273 [info ] [MainThread]: python path: /Users/samstreumer/.pyenv/versions/3.10.0/bin/python
[0m13:18:36.510439 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m13:18:36.510777 [error] [MainThread]: Encountered an error:
local variable 'summary_message' referenced before assignment
[0m13:18:36.511866 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/samstreumer/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/samstreumer/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/samstreumer/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt/cli/main.py", line 414, in debug
    results = task.run()
  File "/Users/samstreumer/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt/task/debug.py", line 114, in run
    load_profile_status: SubtaskStatus = self._load_profile()
  File "/Users/samstreumer/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt/task/debug.py", line 201, in _load_profile
    profile_names, summary_message = self._choose_profile_names()
  File "/Users/samstreumer/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt/task/debug.py", line 276, in _choose_profile_names
    return profiles, summary_message
UnboundLocalError: local variable 'summary_message' referenced before assignment

[0m13:18:36.512781 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.026420083, "process_in_blocks": "0", "process_kernel_time": 0.126482, "process_mem_max_rss": "97615872", "process_out_blocks": "0", "process_user_time": 0.78772}
[0m13:18:36.513088 [debug] [MainThread]: Command `dbt debug` failed at 13:18:36.513038 after 0.03 seconds
[0m13:18:36.513290 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104f778e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077c3c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10786fd30>]}
[0m13:18:36.513495 [debug] [MainThread]: Flushing usage events
[0m13:18:36.916269 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:19:44.978726 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054239a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10672fcd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10672ef50>]}


============================== 13:19:44.982509 | 94e1949b-a078-4431-a999-0cae16a406bf ==============================
[0m13:19:44.982509 [info ] [MainThread]: Running with dbt=1.9.8
[0m13:19:44.982913 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/samstreumer/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:19:44.983358 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/samstreumer/Documents/SchoolFolder/dvdrental/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:19:44.984595 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.015649583, "process_in_blocks": "0", "process_kernel_time": 0.117769, "process_mem_max_rss": "96043008", "process_out_blocks": "0", "process_user_time": 0.762476}
[0m13:19:44.984985 [debug] [MainThread]: Command `dbt run` failed at 13:19:44.984925 after 0.02 seconds
[0m13:19:44.985214 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054239a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10672f190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10672f970>]}
[0m13:19:44.985423 [debug] [MainThread]: Flushing usage events
[0m13:19:45.384979 [debug] [MainThread]: An error was encountered while trying to flush usage events
